### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by barhom** [gl-inet-builder/openwrt-sdk-ipq_ipq60xx-qsdk11#1]
System: Ubuntu 18.04

```
git clone https://github.com/gl-inet-builder/openwrt-sdk-ipq_ipq60xx-qsdk11.git
cd openwrt-sdk-ipq_ipq60xx-qsdk11
./scripts/feeds update
make -j8 V=s
```

This does not complete as it is right now.

```
Package libopenldap is missing dependencies for the following libraries:
libgnutls.so.30
Makefile:146: recipe for target '/home/ibrahim/glinet/sdk/sdk/qsdk11/ipq_ipq60xx/bin/ipq/packages/packages/libopenldap_2.4.44-1_ipq.ipk' failed
make[3]: *** [/home/ibrahim/glinet/sdk/sdk/qsdk11/ipq_ipq60xx/bin/ipq/packages/packages/libopenldap_2.4.44-1_ipq.ipk] Error 1
make[3]: Leaving directory '/home/ibrahim/glinet/sdk/sdk/qsdk11/ipq_ipq60xx/feeds/base/qca/feeds/packages/libs/openldap'
package/Makefile:191: recipe for target 'package/feeds/packages/openldap/compile' failed
make[2]: *** [package/feeds/packages/openldap/compile] Error 2
make[2]: Leaving directory '/home/ibrahim/glinet/sdk/sdk/qsdk11/ipq_ipq60xx'
package/Makefile:188: recipe for target '/home/ibrahim/glinet/sdk/sdk/qsdk11/ipq_ipq60xx/staging_dir/target-arm_cortex-a7_musl-1.1.16_eabi/stamp/.package_compile' failed
make[1]: *** [/home/ibrahim/glinet/sdk/sdk/qsdk11/ipq_ipq60xx/staging_dir/target-arm_cortex-a7_musl-1.1.16_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ibrahim/glinet/sdk/sdk/qsdk11/ipq_ipq60xx'
/home/ibrahim/glinet/sdk/sdk/qsdk11/ipq_ipq60xx/include/toplevel.mk:179: recipe for target 'world' failed
make: *** [world] Error 2
```

**Comment by handongming** [comment]
Actually, if you compile all ipk, there are indeed a lot of errors as of the sdk is 15.05 based. It's primary purpose is to compile a single package. I suggest you only add necessary feeds source to sdk/package directory.
When you use imagebuilder to build firmware, it will download dependent ipk at http://download.gl-inet.com/releases/qsdk_v11/packages-3.x/

**Comment by barhom** [comment]
> Actually, if you compile all ipk, there are indeed a lot of errors as of the sdk is 15.05 based. It's primary purpose is to compile a single package. I suggest you only add necessary feeds source to sdk/package directory. When you use imagebuilder to build firmware, it will download dependent ipk at http://download.gl-inet.com/releases/qsdk_v11/packages-3.x/

Actually I tried to run make without installing all packages.
So do you mean that this SDK should only be used to build ipk and not to build the firmware?

**Comment by handongming** [comment]
Yes, to build the firmware, should use https://github.com/gl-inet/imagebuilder, and it finally links to https://github.com/gl-inet-builder/openwrt-imagebuilder-ipq-ipq60xx-QSDK_Premium_3.5

**Comment by barhom** [comment]
Thank you,
